### ISSUE TITLE
The SCRUM team

### ISSUE THREAD

**Issue by CapperBA** [SorenTheSmed/SCRUMtest#19]
Hvilke roller er der i teamet, og hvilket ansvar har hver rolle?

**Comment by Nicklas2902** [comment]
Product Owner
Denne er ansvarlig for produktet og planlægge leverancerne til kunden igennem en effektiv kravstyring.

Scrum Master
Scrum Master har til opgave at sikre en succesfuld gennemførelse af de enkelte sprints og samtidig synliggøre fremdriften for product owner.

Development Team
Holdet er ansvarlig for at færdiggøre de enkelte sprints indenfor de fastsatte budgetter.

**Comment by anderstofte** [comment]
Hvem udvikler så? Hmmmmmm

**Comment by CapperBA** [comment]
Hvad menes der med kravstyrring?

**Comment by SorenTheSmed** [comment]
Specificér Daniel og Nicklas. Uddyb gerne lige Development Team og udviklere

**Comment by DanielBoebel** [comment]
Håndtering af krav er den største enkelte udfordring i softwareprojekter i dag. En struktureret tilgang til kravhåndtering kan forbedre et projekts chancer for succes mange gange.

**Comment by Nicklas2902** [comment]
Product Owner
Denne er ansvarlig for produktet og planlægge leverancerne til kunden igennem en effektiv kravstyring.
Scrum Master
Scrum Master har til opgave at sikre en succesfuld gennemførelse af de enkelte sprints og samtidig synliggøre fremdriften for product owner.
Development Team
Holdet er ansvarlig for at færdiggøre de enkelte sprints indenfor de fastsatte budgetter.

Håndtering af krav er den største enkelte udfordring i softwareprojekter i dag. En struktureret tilgang til kravhåndtering kan forbedre et projekts chancer for succes mange gange.

**Comment by CapperBA** [comment]
Hvor mange personer er med i hver rolle?

**Comment by Nicklas2902** [comment]
Product Owner
Denne er ansvarlig for produktet og planlægge leverancerne til kunden igennem en effektiv kravstyring.* Product Owner er normalt kun mellem 1 og 4 personer. Det er en eller flere repræsentanter fra kunden og det afhænger af hvor stor en kunde det er.
 
Scrum Master
Scrum Master har til opgave at sikre en succesfuld gennemførelse af de enkelte sprints og samtidig synliggøre fremdriften for product owner. Scrum Master er normalt kun 1 person som også er kaldet projekt leder.

Development Team
Holdet er ansvarlig for at færdiggøre de enkelte sprints indenfor de fastsatte budgetter.
*Håndtering af krav er den største enkelte udfordring i softwareprojekter i dag. En struktureret tilgang til kravhåndtering kan forbedre et projekts chancer for succes mange gange. Development Team er normalt en større gruppe udviklere. Igen kommer størrelsen an på størrelsen af opgaven plus størrelsen af selskabet.

**Comment by SorenTheSmed** [comment]
Ser godt ud. Godt I fik det uddybet. Jeg sender det til kunden og giver jer en update, når jeg har hørt fra kunden.

**Comment by CapperBA** [comment]
Ser fint ud. Jeg har snakket med kunden, og de er yderst tilfreds med jeres forklaringer. De ser frem til flere guldkorn fra jer. :) 
Mvh Product Owner
